const initData = [
    {
        name: "John Doe",
        uid: "100001",
        ign: "JDoe",
        role: "Duelist",
        verificationScreenshot: "screenshot1.png",
    },
    {
        name: "Jane Smith",
        uid: "100002",
        ign: "JSmith",
        role: "Initiator",
        verificationScreenshot: "screenshot2.png",
    },
    {
        name: "Mike Johnson",
        uid: "100003",
        ign: "MJohnson",
        role: "Controller",
        verificationScreenshot: "screenshot3.png",
    },
    {
        name: "Alex Carter",
        uid: "100004",
        ign: "AxCarter",
        role: "Sentinel",
        verificationScreenshot: "screenshot4.png",
    },
    {
        name: "Ryan Patel",
        uid: "100005",
        ign: "RPatel",
        role: "Flex",
        verificationScreenshot: "screenshot5.png",
    },
    {
        name: "Sara Kim",
        uid: "100006",
        ign: "SKim",
        role: "Duelist",
        verificationScreenshot: "screenshot6.png",
    },
    {
        name: "Daniel Lee",
        uid: "100007",
        ign: "DLee",
        role: "Sentinel",
        verificationScreenshot: "screenshot7.png",
    },
    {
        name: "Emily Davis",
        uid: "100008",
        ign: "EDavis",
        role: "Initiator",
        verificationScreenshot: "screenshot8.png",
    },
    {
        name: "Chris Wong",
        uid: "100009",
        ign: "CWong",
        role: "Controller",
        verificationScreenshot: "screenshot9.png",
    },
    {
        name: "Priya Nair",
        uid: "100010",
        ign: "PNair",
        role: "Duelist",
        verificationScreenshot: "screenshot10.png",
    },
    {
        name: "Tom Baker",
        uid: "100011",
        ign: "TBaker",
        role: "Flex",
        verificationScreenshot: "screenshot11.png",
    },
    {
        name: "Nina Rodriguez",
        uid: "100012",
        ign: "NRodriguez",
        role: "Sentinel",
        verificationScreenshot: "screenshot12.png",
    },
    {
        name: "Kevin Zhang",
        uid: "100013",
        ign: "KZhang",
        role: "Initiator",
        verificationScreenshot: "screenshot13.png",
    },
    {
        name: "Olivia Brown",
        uid: "100014",
        ign: "OBrown",
        role: "Controller",
        verificationScreenshot: "screenshot14.png",
    },
    {
        name: "Arjun Mehta",
        uid: "100015",
        ign: "AMehta",
        role: "Duelist",
        verificationScreenshot: "screenshot15.png",
    },
];

export default initData;